// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage_schema.proto

package schema_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogicType int32

const (
	LogicType_NA                LogicType = 0
	LogicType_BOOL              LogicType = 1
	LogicType_UINT8             LogicType = 2
	LogicType_INT8              LogicType = 3
	LogicType_UINT16            LogicType = 4
	LogicType_INT16             LogicType = 5
	LogicType_UINT32            LogicType = 6
	LogicType_INT32             LogicType = 7
	LogicType_UINT64            LogicType = 8
	LogicType_INT64             LogicType = 9
	LogicType_HALF_FLOAT        LogicType = 10
	LogicType_FLOAT             LogicType = 11
	LogicType_DOUBLE            LogicType = 12
	LogicType_STRING            LogicType = 13
	LogicType_BINARY            LogicType = 14
	LogicType_FIXED_SIZE_BINARY LogicType = 15
	// DATE32 = 16;
	// DATE64 = 17;
	// TIMESTAMP = 18;
	// TIME32 = 19;
	// TIME64 = 20;
	// INTERVAL_MONTHS = 21;
	// INTERVAL_DAY_TIME = 22;
	// DECIMAL128 = 23;
	// option allow_alias = true;
	// DECIMAL = 23;  // DECIMAL==DECIMAL128
	// DECIMAL256 = 24;
	LogicType_LIST   LogicType = 25
	LogicType_STRUCT LogicType = 26
	// SPARSE_UNION = 27;
	// DENSE_UNION = 28;
	LogicType_DICTIONARY LogicType = 29
	LogicType_MAP        LogicType = 30
	// EXTENSION = 31;
	LogicType_FIXED_SIZE_LIST LogicType = 32
	// DURATION = 33;
	// LARGE_STRING = 34;
	// LARGE_BINARY = 35;
	// LARGE_LIST = 36;
	// INTERVAL_MONTH_DAY_NANO = 37;
	// RUN_END_ENCODED = 38;
	LogicType_MAX_ID LogicType = 39
)

var LogicType_name = map[int32]string{
	0:  "NA",
	1:  "BOOL",
	2:  "UINT8",
	3:  "INT8",
	4:  "UINT16",
	5:  "INT16",
	6:  "UINT32",
	7:  "INT32",
	8:  "UINT64",
	9:  "INT64",
	10: "HALF_FLOAT",
	11: "FLOAT",
	12: "DOUBLE",
	13: "STRING",
	14: "BINARY",
	15: "FIXED_SIZE_BINARY",
	25: "LIST",
	26: "STRUCT",
	29: "DICTIONARY",
	30: "MAP",
	32: "FIXED_SIZE_LIST",
	39: "MAX_ID",
}

var LogicType_value = map[string]int32{
	"NA":                0,
	"BOOL":              1,
	"UINT8":             2,
	"INT8":              3,
	"UINT16":            4,
	"INT16":             5,
	"UINT32":            6,
	"INT32":             7,
	"UINT64":            8,
	"INT64":             9,
	"HALF_FLOAT":        10,
	"FLOAT":             11,
	"DOUBLE":            12,
	"STRING":            13,
	"BINARY":            14,
	"FIXED_SIZE_BINARY": 15,
	"LIST":              25,
	"STRUCT":            26,
	"DICTIONARY":        29,
	"MAP":               30,
	"FIXED_SIZE_LIST":   32,
	"MAX_ID":            39,
}

func (x LogicType) String() string {
	return proto.EnumName(LogicType_name, int32(x))
}

func (LogicType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{0}
}

type Endianness int32

const (
	Endianness_Little Endianness = 0
	Endianness_Big    Endianness = 1
)

var Endianness_name = map[int32]string{
	0: "Little",
	1: "Big",
}

var Endianness_value = map[string]int32{
	"Little": 0,
	"Big":    1,
}

func (x Endianness) String() string {
	return proto.EnumName(Endianness_name, int32(x))
}

func (Endianness) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{1}
}

type FixedSizeBinaryType struct {
	ByteWidth            int32    `protobuf:"varint,1,opt,name=byte_width,json=byteWidth,proto3" json:"byte_width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixedSizeBinaryType) Reset()         { *m = FixedSizeBinaryType{} }
func (m *FixedSizeBinaryType) String() string { return proto.CompactTextString(m) }
func (*FixedSizeBinaryType) ProtoMessage()    {}
func (*FixedSizeBinaryType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{0}
}

func (m *FixedSizeBinaryType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedSizeBinaryType.Unmarshal(m, b)
}
func (m *FixedSizeBinaryType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedSizeBinaryType.Marshal(b, m, deterministic)
}
func (m *FixedSizeBinaryType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedSizeBinaryType.Merge(m, src)
}
func (m *FixedSizeBinaryType) XXX_Size() int {
	return xxx_messageInfo_FixedSizeBinaryType.Size(m)
}
func (m *FixedSizeBinaryType) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedSizeBinaryType.DiscardUnknown(m)
}

var xxx_messageInfo_FixedSizeBinaryType proto.InternalMessageInfo

func (m *FixedSizeBinaryType) GetByteWidth() int32 {
	if m != nil {
		return m.ByteWidth
	}
	return 0
}

type FixedSizeListType struct {
	ListSize             int32    `protobuf:"varint,1,opt,name=list_size,json=listSize,proto3" json:"list_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixedSizeListType) Reset()         { *m = FixedSizeListType{} }
func (m *FixedSizeListType) String() string { return proto.CompactTextString(m) }
func (*FixedSizeListType) ProtoMessage()    {}
func (*FixedSizeListType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{1}
}

func (m *FixedSizeListType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedSizeListType.Unmarshal(m, b)
}
func (m *FixedSizeListType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedSizeListType.Marshal(b, m, deterministic)
}
func (m *FixedSizeListType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedSizeListType.Merge(m, src)
}
func (m *FixedSizeListType) XXX_Size() int {
	return xxx_messageInfo_FixedSizeListType.Size(m)
}
func (m *FixedSizeListType) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedSizeListType.DiscardUnknown(m)
}

var xxx_messageInfo_FixedSizeListType proto.InternalMessageInfo

func (m *FixedSizeListType) GetListSize() int32 {
	if m != nil {
		return m.ListSize
	}
	return 0
}

type DictionaryType struct {
	IndexType            *DataType `protobuf:"bytes,1,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	ValueType            *DataType `protobuf:"bytes,2,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Ordered              bool      `protobuf:"varint,3,opt,name=ordered,proto3" json:"ordered,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DictionaryType) Reset()         { *m = DictionaryType{} }
func (m *DictionaryType) String() string { return proto.CompactTextString(m) }
func (*DictionaryType) ProtoMessage()    {}
func (*DictionaryType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{2}
}

func (m *DictionaryType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryType.Unmarshal(m, b)
}
func (m *DictionaryType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryType.Marshal(b, m, deterministic)
}
func (m *DictionaryType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryType.Merge(m, src)
}
func (m *DictionaryType) XXX_Size() int {
	return xxx_messageInfo_DictionaryType.Size(m)
}
func (m *DictionaryType) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryType.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryType proto.InternalMessageInfo

func (m *DictionaryType) GetIndexType() *DataType {
	if m != nil {
		return m.IndexType
	}
	return nil
}

func (m *DictionaryType) GetValueType() *DataType {
	if m != nil {
		return m.ValueType
	}
	return nil
}

func (m *DictionaryType) GetOrdered() bool {
	if m != nil {
		return m.Ordered
	}
	return false
}

type MapType struct {
	KeysSorted           bool     `protobuf:"varint,1,opt,name=keys_sorted,json=keysSorted,proto3" json:"keys_sorted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapType) Reset()         { *m = MapType{} }
func (m *MapType) String() string { return proto.CompactTextString(m) }
func (*MapType) ProtoMessage()    {}
func (*MapType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{3}
}

func (m *MapType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapType.Unmarshal(m, b)
}
func (m *MapType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapType.Marshal(b, m, deterministic)
}
func (m *MapType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapType.Merge(m, src)
}
func (m *MapType) XXX_Size() int {
	return xxx_messageInfo_MapType.Size(m)
}
func (m *MapType) XXX_DiscardUnknown() {
	xxx_messageInfo_MapType.DiscardUnknown(m)
}

var xxx_messageInfo_MapType proto.InternalMessageInfo

func (m *MapType) GetKeysSorted() bool {
	if m != nil {
		return m.KeysSorted
	}
	return false
}

type DataType struct {
	// Types that are valid to be assigned to TypeRelatedValues:
	//
	//	*DataType_FixedSizeBinaryType
	//	*DataType_FixedSizeListType
	//	*DataType_DictionaryType
	//	*DataType_MapType
	TypeRelatedValues    isDataType_TypeRelatedValues `protobuf_oneof:"type_related_values"`
	LogicType            LogicType                    `protobuf:"varint,100,opt,name=logic_type,json=logicType,proto3,enum=schema_proto.LogicType" json:"logic_type,omitempty"`
	Children             []*Field                     `protobuf:"bytes,101,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DataType) Reset()         { *m = DataType{} }
func (m *DataType) String() string { return proto.CompactTextString(m) }
func (*DataType) ProtoMessage()    {}
func (*DataType) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{4}
}

func (m *DataType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataType.Unmarshal(m, b)
}
func (m *DataType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataType.Marshal(b, m, deterministic)
}
func (m *DataType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataType.Merge(m, src)
}
func (m *DataType) XXX_Size() int {
	return xxx_messageInfo_DataType.Size(m)
}
func (m *DataType) XXX_DiscardUnknown() {
	xxx_messageInfo_DataType.DiscardUnknown(m)
}

var xxx_messageInfo_DataType proto.InternalMessageInfo

type isDataType_TypeRelatedValues interface {
	isDataType_TypeRelatedValues()
}

type DataType_FixedSizeBinaryType struct {
	FixedSizeBinaryType *FixedSizeBinaryType `protobuf:"bytes,1,opt,name=fixed_size_binary_type,json=fixedSizeBinaryType,proto3,oneof"`
}

type DataType_FixedSizeListType struct {
	FixedSizeListType *FixedSizeListType `protobuf:"bytes,2,opt,name=fixed_size_list_type,json=fixedSizeListType,proto3,oneof"`
}

type DataType_DictionaryType struct {
	DictionaryType *DictionaryType `protobuf:"bytes,3,opt,name=dictionary_type,json=dictionaryType,proto3,oneof"`
}

type DataType_MapType struct {
	MapType *MapType `protobuf:"bytes,4,opt,name=map_type,json=mapType,proto3,oneof"`
}

func (*DataType_FixedSizeBinaryType) isDataType_TypeRelatedValues() {}

func (*DataType_FixedSizeListType) isDataType_TypeRelatedValues() {}

func (*DataType_DictionaryType) isDataType_TypeRelatedValues() {}

func (*DataType_MapType) isDataType_TypeRelatedValues() {}

func (m *DataType) GetTypeRelatedValues() isDataType_TypeRelatedValues {
	if m != nil {
		return m.TypeRelatedValues
	}
	return nil
}

func (m *DataType) GetFixedSizeBinaryType() *FixedSizeBinaryType {
	if x, ok := m.GetTypeRelatedValues().(*DataType_FixedSizeBinaryType); ok {
		return x.FixedSizeBinaryType
	}
	return nil
}

func (m *DataType) GetFixedSizeListType() *FixedSizeListType {
	if x, ok := m.GetTypeRelatedValues().(*DataType_FixedSizeListType); ok {
		return x.FixedSizeListType
	}
	return nil
}

func (m *DataType) GetDictionaryType() *DictionaryType {
	if x, ok := m.GetTypeRelatedValues().(*DataType_DictionaryType); ok {
		return x.DictionaryType
	}
	return nil
}

func (m *DataType) GetMapType() *MapType {
	if x, ok := m.GetTypeRelatedValues().(*DataType_MapType); ok {
		return x.MapType
	}
	return nil
}

func (m *DataType) GetLogicType() LogicType {
	if m != nil {
		return m.LogicType
	}
	return LogicType_NA
}

func (m *DataType) GetChildren() []*Field {
	if m != nil {
		return m.Children
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataType_FixedSizeBinaryType)(nil),
		(*DataType_FixedSizeListType)(nil),
		(*DataType_DictionaryType)(nil),
		(*DataType_MapType)(nil),
	}
}

type KeyValueMetadata struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValueMetadata) Reset()         { *m = KeyValueMetadata{} }
func (m *KeyValueMetadata) String() string { return proto.CompactTextString(m) }
func (*KeyValueMetadata) ProtoMessage()    {}
func (*KeyValueMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{5}
}

func (m *KeyValueMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValueMetadata.Unmarshal(m, b)
}
func (m *KeyValueMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValueMetadata.Marshal(b, m, deterministic)
}
func (m *KeyValueMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValueMetadata.Merge(m, src)
}
func (m *KeyValueMetadata) XXX_Size() int {
	return xxx_messageInfo_KeyValueMetadata.Size(m)
}
func (m *KeyValueMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValueMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValueMetadata proto.InternalMessageInfo

func (m *KeyValueMetadata) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *KeyValueMetadata) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Field struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nullable             bool              `protobuf:"varint,2,opt,name=nullable,proto3" json:"nullable,omitempty"`
	DataType             *DataType         `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Metadata             *KeyValueMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{6}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Field) GetDataType() *DataType {
	if m != nil {
		return m.DataType
	}
	return nil
}

func (m *Field) GetMetadata() *KeyValueMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SchemaOptions struct {
	PrimaryColumn        string   `protobuf:"bytes,1,opt,name=primary_column,json=primaryColumn,proto3" json:"primary_column,omitempty"`
	VersionColumn        string   `protobuf:"bytes,2,opt,name=version_column,json=versionColumn,proto3" json:"version_column,omitempty"`
	VectorColumn         string   `protobuf:"bytes,3,opt,name=vector_column,json=vectorColumn,proto3" json:"vector_column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemaOptions) Reset()         { *m = SchemaOptions{} }
func (m *SchemaOptions) String() string { return proto.CompactTextString(m) }
func (*SchemaOptions) ProtoMessage()    {}
func (*SchemaOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{7}
}

func (m *SchemaOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaOptions.Unmarshal(m, b)
}
func (m *SchemaOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaOptions.Marshal(b, m, deterministic)
}
func (m *SchemaOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaOptions.Merge(m, src)
}
func (m *SchemaOptions) XXX_Size() int {
	return xxx_messageInfo_SchemaOptions.Size(m)
}
func (m *SchemaOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaOptions.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaOptions proto.InternalMessageInfo

func (m *SchemaOptions) GetPrimaryColumn() string {
	if m != nil {
		return m.PrimaryColumn
	}
	return ""
}

func (m *SchemaOptions) GetVersionColumn() string {
	if m != nil {
		return m.VersionColumn
	}
	return ""
}

func (m *SchemaOptions) GetVectorColumn() string {
	if m != nil {
		return m.VectorColumn
	}
	return ""
}

type ArrowSchema struct {
	Fields               []*Field          `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Endianness           Endianness        `protobuf:"varint,2,opt,name=endianness,proto3,enum=schema_proto.Endianness" json:"endianness,omitempty"`
	Metadata             *KeyValueMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ArrowSchema) Reset()         { *m = ArrowSchema{} }
func (m *ArrowSchema) String() string { return proto.CompactTextString(m) }
func (*ArrowSchema) ProtoMessage()    {}
func (*ArrowSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{8}
}

func (m *ArrowSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrowSchema.Unmarshal(m, b)
}
func (m *ArrowSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrowSchema.Marshal(b, m, deterministic)
}
func (m *ArrowSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrowSchema.Merge(m, src)
}
func (m *ArrowSchema) XXX_Size() int {
	return xxx_messageInfo_ArrowSchema.Size(m)
}
func (m *ArrowSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrowSchema.DiscardUnknown(m)
}

var xxx_messageInfo_ArrowSchema proto.InternalMessageInfo

func (m *ArrowSchema) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ArrowSchema) GetEndianness() Endianness {
	if m != nil {
		return m.Endianness
	}
	return Endianness_Little
}

func (m *ArrowSchema) GetMetadata() *KeyValueMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Schema struct {
	ArrowSchema          *ArrowSchema   `protobuf:"bytes,1,opt,name=arrow_schema,json=arrowSchema,proto3" json:"arrow_schema,omitempty"`
	SchemaOptions        *SchemaOptions `protobuf:"bytes,2,opt,name=schema_options,json=schemaOptions,proto3" json:"schema_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8f8ddeefeee12bd, []int{9}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetArrowSchema() *ArrowSchema {
	if m != nil {
		return m.ArrowSchema
	}
	return nil
}

func (m *Schema) GetSchemaOptions() *SchemaOptions {
	if m != nil {
		return m.SchemaOptions
	}
	return nil
}

func init() {
	proto.RegisterEnum("schema_proto.LogicType", LogicType_name, LogicType_value)
	proto.RegisterEnum("schema_proto.Endianness", Endianness_name, Endianness_value)
	proto.RegisterType((*FixedSizeBinaryType)(nil), "schema_proto.FixedSizeBinaryType")
	proto.RegisterType((*FixedSizeListType)(nil), "schema_proto.FixedSizeListType")
	proto.RegisterType((*DictionaryType)(nil), "schema_proto.DictionaryType")
	proto.RegisterType((*MapType)(nil), "schema_proto.MapType")
	proto.RegisterType((*DataType)(nil), "schema_proto.DataType")
	proto.RegisterType((*KeyValueMetadata)(nil), "schema_proto.KeyValueMetadata")
	proto.RegisterType((*Field)(nil), "schema_proto.Field")
	proto.RegisterType((*SchemaOptions)(nil), "schema_proto.SchemaOptions")
	proto.RegisterType((*ArrowSchema)(nil), "schema_proto.ArrowSchema")
	proto.RegisterType((*Schema)(nil), "schema_proto.Schema")
}

func init() { proto.RegisterFile("storage_schema.proto", fileDescriptor_a8f8ddeefeee12bd) }

var fileDescriptor_a8f8ddeefeee12bd = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5d, 0x6f, 0x1a, 0x47,
	0x14, 0x65, 0xc1, 0x86, 0xe5, 0x62, 0xf0, 0x78, 0x88, 0x5d, 0x92, 0x34, 0x09, 0xd9, 0xaa, 0x2a,
	0x72, 0x55, 0xd3, 0x62, 0xd7, 0x4a, 0x3f, 0x54, 0x09, 0x8c, 0x1d, 0x56, 0xc5, 0xa6, 0x1a, 0x70,
	0xeb, 0xe6, 0x65, 0xb5, 0xb0, 0x63, 0x3c, 0xea, 0x7e, 0xa0, 0xdd, 0xc5, 0x09, 0x79, 0xec, 0x63,
	0x7f, 0x41, 0x5f, 0xfa, 0xde, 0xc7, 0xbe, 0xf4, 0xff, 0x55, 0xf3, 0xb1, 0x74, 0xd7, 0x8d, 0x2b,
	0xe5, 0xc9, 0x77, 0xce, 0x9c, 0x73, 0xe7, 0xce, 0x39, 0xb3, 0x06, 0x1e, 0x44, 0x71, 0x10, 0xda,
	0x73, 0x6a, 0x45, 0xb3, 0x1b, 0xea, 0xd9, 0x07, 0x8b, 0x30, 0x88, 0x03, 0xbc, 0x25, 0x57, 0x96,
	0x58, 0x19, 0x47, 0x50, 0x3f, 0x63, 0x6f, 0xa8, 0x33, 0x66, 0x6f, 0x69, 0x8f, 0xf9, 0x76, 0xb8,
	0x9a, 0xac, 0x16, 0x14, 0x3f, 0x01, 0x98, 0xae, 0x62, 0x6a, 0xbd, 0x66, 0x4e, 0x7c, 0xd3, 0xd0,
	0x9a, 0x5a, 0x6b, 0x93, 0x94, 0x39, 0xf2, 0x13, 0x07, 0x8c, 0xcf, 0x61, 0x67, 0xad, 0x1a, 0xb2,
	0x28, 0x16, 0x9a, 0xc7, 0x50, 0x76, 0x59, 0x14, 0x5b, 0x11, 0x7b, 0x4b, 0x95, 0x44, 0xe7, 0x00,
	0x27, 0x19, 0xbf, 0x6b, 0x50, 0xeb, 0xb3, 0x59, 0xcc, 0x82, 0xf5, 0x19, 0x5f, 0x02, 0x30, 0xdf,
	0xa1, 0x6f, 0xac, 0x78, 0xb5, 0x90, 0x82, 0x4a, 0x67, 0xef, 0x20, 0x3d, 0xdd, 0x41, 0xdf, 0x8e,
	0x6d, 0xce, 0x25, 0x65, 0xc1, 0x4c, 0x64, 0xb7, 0xb6, 0xbb, 0xa4, 0x52, 0x96, 0xff, 0x7f, 0x99,
	0x60, 0x0a, 0x59, 0x03, 0x4a, 0x41, 0xe8, 0xd0, 0x90, 0x3a, 0x8d, 0x42, 0x53, 0x6b, 0xe9, 0x24,
	0x59, 0x1a, 0xfb, 0x50, 0x3a, 0xb7, 0x17, 0x82, 0xf4, 0x0c, 0x2a, 0xbf, 0xd0, 0x55, 0x64, 0x45,
	0x41, 0x18, 0x53, 0x47, 0xcc, 0xa4, 0x13, 0xe0, 0xd0, 0x58, 0x20, 0xc6, 0xdf, 0x05, 0xd0, 0x93,
	0xee, 0xf8, 0x0a, 0xf6, 0xae, 0xb9, 0x0b, 0xe2, 0xc6, 0xd6, 0x54, 0xb8, 0x97, 0xbe, 0xcc, 0xf3,
	0xec, 0x54, 0xef, 0xf0, 0x79, 0x90, 0x23, 0xf5, 0xeb, 0x77, 0xd8, 0x4f, 0xe0, 0x41, 0xaa, 0xb3,
	0x70, 0x35, 0x75, 0xdb, 0x67, 0xf7, 0xf4, 0x4d, 0x92, 0x18, 0xe4, 0xc8, 0xce, 0xf5, 0x7f, 0xe2,
	0x79, 0x09, 0xdb, 0xce, 0x3a, 0x00, 0xd9, 0xae, 0x20, 0xda, 0x7d, 0x78, 0xc7, 0xbc, 0x4c, 0x4a,
	0x83, 0x1c, 0xa9, 0x39, 0xd9, 0xdc, 0x3a, 0xa0, 0x7b, 0xf6, 0x42, 0x76, 0xd8, 0x10, 0x1d, 0x76,
	0xb3, 0x1d, 0x94, 0x9b, 0x83, 0x1c, 0x29, 0x79, 0xca, 0xd8, 0x63, 0x00, 0x37, 0x98, 0xb3, 0x99,
	0x54, 0x39, 0x4d, 0xad, 0x55, 0xeb, 0x7c, 0x90, 0x55, 0x0d, 0xf9, 0xbe, 0x4c, 0xcd, 0x4d, 0x4a,
	0xdc, 0x06, 0x7d, 0x76, 0xc3, 0x5c, 0x27, 0xa4, 0x7e, 0x83, 0x36, 0x0b, 0xad, 0x4a, 0xa7, 0x7e,
	0xf7, 0xf2, 0xd4, 0x75, 0xc8, 0x9a, 0xd4, 0xdb, 0x85, 0x3a, 0x3f, 0xc2, 0x0a, 0xa9, 0x6b, 0xc7,
	0xd4, 0xb1, 0xc4, 0x03, 0x88, 0x8c, 0xef, 0x00, 0x7d, 0x4f, 0x57, 0x3f, 0xf2, 0xc5, 0x39, 0x8d,
	0x6d, 0xc7, 0x8e, 0x6d, 0x8c, 0x61, 0x83, 0x27, 0xdb, 0xd0, 0x9a, 0x85, 0x56, 0x99, 0x88, 0x1a,
	0xef, 0x41, 0x51, 0x2a, 0x1a, 0x79, 0x81, 0xaa, 0x95, 0xf1, 0xa7, 0x06, 0x9b, 0xe2, 0x28, 0xae,
	0xf2, 0x6d, 0x4f, 0x46, 0x5c, 0x26, 0xa2, 0xc6, 0x8f, 0x40, 0xf7, 0x97, 0xae, 0x6b, 0x4f, 0x5d,
	0x19, 0x91, 0x4e, 0xd6, 0x6b, 0x7c, 0x08, 0x65, 0x7e, 0x5a, 0xda, 0xf0, 0xfb, 0x5e, 0xab, 0xee,
	0x24, 0x2f, 0xeb, 0x6b, 0xd0, 0x3d, 0x35, 0xa6, 0xb2, 0xf8, 0x69, 0x56, 0x73, 0xf7, 0x32, 0x64,
	0xcd, 0x37, 0x7e, 0xd5, 0xa0, 0x3a, 0x16, 0xdc, 0xd1, 0x82, 0xc7, 0x16, 0xe1, 0x8f, 0xa1, 0xb6,
	0x08, 0x99, 0xc7, 0x63, 0x9f, 0x05, 0xee, 0xd2, 0xf3, 0xd5, 0xf0, 0x55, 0x85, 0x9e, 0x08, 0x90,
	0xd3, 0x6e, 0x69, 0x18, 0xb1, 0xc0, 0x4f, 0x68, 0x79, 0x49, 0x53, 0xa8, 0xa2, 0x7d, 0x04, 0xd5,
	0x5b, 0x3a, 0x8b, 0x83, 0x30, 0x61, 0x15, 0x04, 0x6b, 0x4b, 0x82, 0x92, 0x64, 0xfc, 0xa5, 0x41,
	0xa5, 0x1b, 0x86, 0xc1, 0x6b, 0x39, 0x09, 0xfe, 0x14, 0x8a, 0xd7, 0xdc, 0x3e, 0xe9, 0xf6, 0x3d,
	0x29, 0x2a, 0x0a, 0x7e, 0x01, 0x40, 0x7d, 0x87, 0xd9, 0xbe, 0x4f, 0xa3, 0x48, 0x0c, 0x51, 0xeb,
	0x34, 0xb2, 0x82, 0xd3, 0xf5, 0x3e, 0x49, 0x71, 0x33, 0xbe, 0x15, 0xde, 0xd3, 0xb7, 0xdf, 0x34,
	0x28, 0xaa, 0x69, 0xbf, 0x85, 0x2d, 0x9b, 0x0f, 0xaf, 0xfe, 0x71, 0xaa, 0xcf, 0xf9, 0x61, 0xb6,
	0x55, 0xea, 0x7a, 0xa4, 0x62, 0xa7, 0xee, 0xda, 0x83, 0x9a, 0x22, 0x06, 0x32, 0x00, 0xf5, 0xd9,
	0x3e, 0xce, 0xea, 0x33, 0x19, 0x91, 0x6a, 0x94, 0x5e, 0xee, 0xff, 0x91, 0x87, 0xf2, 0xfa, 0x83,
	0xc0, 0x45, 0xc8, 0x5f, 0x74, 0x51, 0x0e, 0xeb, 0xb0, 0xd1, 0x1b, 0x8d, 0x86, 0x48, 0xc3, 0x65,
	0xd8, 0xbc, 0x34, 0x2f, 0x26, 0x2f, 0x50, 0x9e, 0x83, 0xa2, 0x2a, 0x60, 0x80, 0x22, 0x07, 0xbf,
	0x38, 0x46, 0x1b, 0x9c, 0x20, 0xcb, 0xcd, 0x04, 0x3e, 0xec, 0xa0, 0xa2, 0x82, 0x0f, 0x3b, 0xa8,
	0x94, 0xc0, 0xc7, 0x47, 0x48, 0x57, 0xf0, 0xf1, 0x11, 0x2a, 0xe3, 0x1a, 0xc0, 0xa0, 0x3b, 0x3c,
	0xb3, 0xce, 0x86, 0xa3, 0xee, 0x04, 0x01, 0xdf, 0x92, 0x65, 0x85, 0x2b, 0xfa, 0xa3, 0xcb, 0xde,
	0xf0, 0x14, 0x6d, 0xf1, 0x7a, 0x3c, 0x21, 0xe6, 0xc5, 0x4b, 0x54, 0xe5, 0x75, 0xcf, 0xbc, 0xe8,
	0x92, 0x9f, 0x51, 0x0d, 0xef, 0xc2, 0xce, 0x99, 0x79, 0x75, 0xda, 0xb7, 0xc6, 0xe6, 0xab, 0x53,
	0x4b, 0xc1, 0xdb, 0x7c, 0xc8, 0xa1, 0x39, 0x9e, 0xa0, 0x87, 0x4a, 0x78, 0x79, 0x32, 0x41, 0x8f,
	0xf8, 0x59, 0x7d, 0xf3, 0x64, 0x62, 0x8e, 0x04, 0xeb, 0x09, 0x2e, 0x41, 0xe1, 0xbc, 0xfb, 0x03,
	0x7a, 0x8a, 0xeb, 0xb0, 0x9d, 0xea, 0x22, 0x94, 0x4d, 0xae, 0x3c, 0xef, 0x5e, 0x59, 0x66, 0x1f,
	0x7d, 0xb2, 0xff, 0x1c, 0xe0, 0xdf, 0x27, 0xc0, 0x77, 0x86, 0x2c, 0x8e, 0x5d, 0x8a, 0x72, 0xbc,
	0x47, 0x8f, 0xcd, 0x91, 0xd6, 0xfb, 0xe6, 0xd5, 0x57, 0x73, 0x16, 0xdf, 0x2c, 0xa7, 0x07, 0xb3,
	0xc0, 0x6b, 0x7b, 0xcc, 0xbd, 0x5d, 0x46, 0x9f, 0xb1, 0x20, 0xa9, 0xd4, 0x6f, 0x63, 0x7b, 0x1e,
	0xb4, 0x45, 0x1e, 0xed, 0x74, 0x38, 0xd3, 0xa2, 0xf8, 0x73, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8d, 0x62, 0x07, 0xa2, 0x43, 0x07, 0x00, 0x00,
}
