// Copyright 2023 Zilliz
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// #ifdef BUILD_WITH_UT

#pragma once

#include <vector>
#include <string>

#include <arrow/type.h>
#include <arrow/status.h>
#include <arrow/result.h>
#include <arrow/filesystem/filesystem.h>

#include "milvus-storage/properties.h"
#include "milvus-storage/filesystem/fs.h"
#include "milvus-storage/common/macro.h"
#include "milvus-storage/common/arrow_util.h"  // for GetEnvVar

// Init common properties for tests
#define ENV_VAR_STORAGE_TYPE "STORAGE_TYPE"
#define ENV_VAR_CLOUD_PROVIDER "CLOUD_PROVIDER"
#define ENV_VAR_ADDRESS "ADDRESS"
#define ENV_VAR_BUCKET_NAME "BUCKET_NAME"
#define ENV_VAR_ACCESS_KEY_ID "ACCESS_KEY"
#define ENV_VAR_ACCESS_KEY_VALUE "SECRET_KEY"
#define ENV_VAR_REGION "REGION"

// only used in local storage
#define ENV_VAR_ROOT_PATH "ROOT_PATH"

#define ASSERT_STATUS_OK(status)                       \
  do {                                                 \
    ASSERT_TRUE((status).ok()) << (status).ToString(); \
  } while (false)

#define ASSERT_STATUS_NOT_OK(status) \
  do {                               \
    ASSERT_FALSE((status).ok());     \
  } while (false)

#define ASSERT_AND_ASSIGN_IMPL(status_name, lhs, rexpr) \
  auto status_name = (rexpr);                           \
  ASSERT_STATUS_OK(status_name.status());               \
  lhs = std::move(status_name).ValueOrDie();

#define ASSERT_AND_ASSIGN(lhs, rexpr) ASSERT_AND_ASSIGN_IMPL(CONCAT(_tmp_value, __COUNTER__), lhs, rexpr);

namespace milvus_storage {
bool IsCloudEnv();
arrow::Status InitTestProperties(api::Properties& properties, std::string address = "/", std::string root_path = "/");
std::string GetTestBasePath(std::string dir);

arrow::Result<milvus_storage::ArrowFileSystemConfig> GetFileSystemConfig(const api::Properties& properties);
arrow::Result<milvus_storage::ArrowFileSystemPtr> GetFileSystem(const api::Properties& properties);
arrow::Status CreateTestDir(const milvus_storage::ArrowFileSystemPtr& fs, const std::string& path);
arrow::Status DeleteTestDir(const milvus_storage::ArrowFileSystemPtr& fs,
                            const std::string& path,
                            bool allow_missing = true);

arrow::Result<std::shared_ptr<arrow::Schema>> CreateTestSchema(std::array<bool, 4> needed_columns = {true, true, true,
                                                                                                     true});
arrow::Result<std::shared_ptr<arrow::RecordBatch>> CreateTestData(std::shared_ptr<arrow::Schema> schema,
                                                                  bool randdata = false,
                                                                  size_t num_rows = 100,
                                                                  size_t vector_dim = 4,
                                                                  size_t str_length = 50,
                                                                  std::array<bool, 4> needed_columns = {true, true,
                                                                                                        true, true});

// which need all columns to be present for validation
// also arrays data generated should not with random values
// eg. generated by CreateTestData(schema);
arrow::Status ValidateRowAlignment(const std::shared_ptr<arrow::RecordBatch>& batch);
}  // namespace milvus_storage

// #endif // BUILD_WITH_UT